### ISSUE TITLE
DockerFile构建失败

### ISSUE THREAD

**Issue by YyItRoad** [ssssssss-team/spider-flow#10]
我使用Docker部署项目，编译DockerFile时出现缺少重要文件。
```
ADD ./spider-flow-web/target/spider-flow.jar ./
```
spider-flow-web目录下无target文件夹及文件。

麻烦可以上传一下吗？

**Comment by nekolr** [comment]
你需要使用 maven 手动编译一下项目

**Comment by nekolr** [comment]
> 
> 
> 我使用Docker部署项目，编译DockerFile时出现缺少重要文件。
> 
> ```
> ADD ./spider-flow-web/target/spider-flow.jar ./
> ```
> 
> spider-flow-web目录下无target文件夹及文件。
> 
> 麻烦可以上传一下吗？

如果你没有用过 maven，那么可以使用 dev 分支进行部署。或者可以参考 dev 分支的 Dockerfile 文件，在你的本地修改 master 分支的 Dockerfile 文件后再尝试部署。

**Comment by YyItRoad** [comment]
谢谢！

**Comment by Lr-2002** [comment]
你好，现在这个项目我用
`mvn compile`
编译过了，而且 Build Sucsess了

但是`docker build -t spider:spider`还是出现上边的`spider-flow.jar not exist `的问题
请问你解决了吗
@YyItRoad

**Comment by nekolr** [comment]
> 你好，现在这个项目我用 `mvn compile` 编译过了，而且 Build Sucsess了
> 
> 但是`docker build -t spider:spider`还是出现上边的`spider-flow.jar not exist `的问题 请问你解决了吗 @YyItRoad

请使用 `mvn clean package` 命令编译并打包，其实你从 Dockerfile 文件执行的命令也能够看出来，它需要的是打包好的 jar 文件

**Comment by Lr-2002** [comment]
好的，解决了，感谢～～～

**Comment by l0o0** [comment]
用 dev 分支里的Dockerfile 创建时，出现下面的报错
```
Sending build context to Docker daemon  2.048kB
Step 1/9 : FROM nekolr/maven:3.6.1 AS build
 ---> 2552d2846d44
Step 2/9 : RUN mkdir -p /usr/src/app
 ---> Using cache
 ---> 364d1d9a4677
Step 3/9 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 1d59ed2b098e
Step 4/9 : COPY . .
 ---> fe4452570d99
Step 5/9 : RUN mvn clean package
 ---> Running in 87d39bf99fcc
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.097 s
[INFO] Finished at: 2022-02-24T02:31:32Z
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/usr/src/app). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
The command '/bin/sh -c mvn clean package' returned a non-zero code: 1
```

**Comment by nekolr** [comment]
> 

请在项目根目录下执行类似以下的命令：

```
docker build -t 8s-team:spider-flow .
```

**Comment by nekolr** [comment]
> 用 dev 分支里的Dockerfile 创建时，出现下面的报错
> 
> ```
> Sending build context to Docker daemon  2.048kB
> Step 1/9 : FROM nekolr/maven:3.6.1 AS build
>  ---> 2552d2846d44
> Step 2/9 : RUN mkdir -p /usr/src/app
>  ---> Using cache
>  ---> 364d1d9a4677
> Step 3/9 : WORKDIR /usr/src/app
>  ---> Using cache
>  ---> 1d59ed2b098e
> Step 4/9 : COPY . .
>  ---> fe4452570d99
> Step 5/9 : RUN mvn clean package
>  ---> Running in 87d39bf99fcc
> [INFO] Scanning for projects...
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  0.097 s
> [INFO] Finished at: 2022-02-24T02:31:32Z
> [INFO] ------------------------------------------------------------------------
> [ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/usr/src/app). Please verify you invoked Maven from the correct directory. -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
> The command '/bin/sh -c mvn clean package' returned a non-zero code: 1
> ```

请在项目根目录下执行类似以下的命令：

```
docker build -t 8s-team:spider-flow .
```

**Comment by l0o0** [comment]
@nekolr 感谢您的回复。我从 dev 分支下载代码后，执行 `docker build -t 8s-team/spider-flow:latest .` 已经能够创建成功了。

不过后面我在宿主机上进行端口映射时后，访问不了 127.0.0.1:8088 。
我进行容器端口映射的代码如下：
`docker run -d -p 127.0.0.1:8088:8088 8s-team/spider-flow:latest`。我看docker file 中暴露的端口为 8088，不知道这个命令有没有问题。

**Comment by nekolr** [comment]
> @nekolr 感谢您的回复。我从 dev 分支下载代码后，执行 `docker build -t 8s-team/spider-flow:latest .` 已经能够创建成功了。
> 
> 不过后面我在宿主机上进行端口映射时后，访问不了 127.0.0.1:8088 。 我进行容器端口映射的代码如下： `docker run -d -p 127.0.0.1:8088:8088 8s-team/spider-flow:latest`。我看docker file 中暴露的端口为 8088，不知道这个命令有没有问题。

命令本身没有问题，访问不了是因为项目没有启动成功，由于它依赖 mysql 服务，因此宿主机需要提供一个 mysql 数据库（安装完 mysql 后记得回到项目里边修改配置文件中 mysql 相关配置，重新构建镜像运行）。
