### ISSUE TITLE
大佬,这个框架非常好用啊,简单易懂,看了更新日志有0.5.1,还有在维护吗

### ISSUE THREAD

**Issue by yx8899** [ssssssss-team/spider-flow#13]
大佬,这个框架非常好用啊,简单易懂,看了更新日志有0.5.1,还有在维护吗

**Comment by nekolr** [comment]
> 
> 
> 大佬,这个框架非常好用啊,简单易懂,看了更新日志有0.5.1,还有在维护吗

功能都已经稳定了，有 bug 可以直接提

**Comment by yx8899** [comment]
可以看到0.5.1新增优化修复了很多功能,但是找不到0.5.1的代码,交流群也不能加了,所以来这里咨询一下

**Comment by nekolr** [comment]
> 
> 
> 可以看到0.5.1新增优化修复了很多功能,但是找不到0.5.1的代码,交流群也不能加了,所以来这里咨询一下

代码都是最新的，只是没有发版罢了

**Comment by yx8899** [comment]
好的,感谢大佬解答
