### ISSUE TITLE
大佬们这个截图要怎么操作呀

### ISSUE THREAD

**Issue by ClaudeJiang** [ssssssss-team/spider-flow#23]
webElement.screen()截下来看到的是空文件
![image](https://user-images.githubusercontent.com/92146151/148041470-83236a5e-d4e0-41bc-8227-839eb67757d6.png)

**Comment by nekolr** [comment]
> webElement.screen()截下来看到的是空文件 ![image](https://user-images.githubusercontent.com/92146151/148041470-83236a5e-d4e0-41bc-8227-839eb67757d6.png)

请仔细看文档，截图的方法是：`screenshot`

**Comment by ClaudeJiang** [comment]
> > webElement.screen()截下来看到的是空文件 ![image](https://user-images.githubusercontent.com/92146151/148041470-83236a5e-d4e0-41bc-8227-839eb67757d6.png)
> 
> 请仔细看文档，截图的方法是：`screenshot`

哦哦不好意思，先前试了几次没成功，在尝试排除其他问题的时候，截图输错了，大佬能说一下这个函数使用的先决条件麽，它可以是通过webElement直接截取这个元素下面的一块区域麽，还是像driver那样截取整个页面的

**Comment by nekolr** [comment]
> 

参考：<https://www.w3.org/TR/webdriver1/#take-element-screenshot>

**Comment by ClaudeJiang** [comment]
> > 
> 
> 参考：https://www.w3.org/TR/webdriver1/#take-element-screenshot

感谢大佬！

**Comment by ClaudeJiang** [comment]
> > 
> 
> 参考：https://www.w3.org/TR/webdriver1/#take-element-screenshot

大佬还有一个问题，就是"开始抓取"这个延迟时间，似乎是等待一段时间再进行链接然后抓取，能不能做到先链接之后等待一段时间再进行抓取呢
