### ISSUE TITLE
请问项目还在维护吗？

### ISSUE THREAD

**Issue by 775146061** [ssssssss-team/spider-flow#26]

**Comment by nekolr** [comment]
> _No description provided._

目前不会有新的功能加入了，有问题可以直接提

**Comment by 775146061** [comment]
想加入你们的群

**Comment by nekolr** [comment]
> 想加入你们的群

群号在这里: https://github.com/ssssssss-team/spider-flow/issues/7#issuecomment-718293907

**Comment by 775146061** [comment]
> #7 (comment)

720832964这个群号没搜到呢
