### ISSUE TITLE
Language file

### ISSUE THREAD

**Issue by Edouardo-m** [ssssssss-team/spider-flow#27]
Hi ! Would like to know if i can translate Spider Flow in english ? Looks like really cool tool but it's a bit confusing for me ^^'

Thanks !

**Comment by nekolr** [comment]
> Hi ! Would like to know if i can translate Spider Flow in english ? Looks like really cool tool but it's a bit confusing for me ^^'
> 
> Thanks !

Of course you can, but you have to know that it's a lot of work to do.
