### ISSUE TITLE
目前项目还有在维护更新嘛？

### ISSUE THREAD

**Issue by tmljob** [ssssssss-team/spider-flow#31]
如题

**Comment by nekolr** [comment]
> 如题

新功能不会添加，有疑问或者项目有严重 bug 可以提交 issue，有能力也可以自行解决。

**Comment by tmljob** [comment]
> > 如题
> 
> 新功能不会添加，有疑问或者项目有严重 bug 可以提交 issue，有能力也可以自行解决。

好的，了解了，刚接触爬虫，感觉这个框架很强大的，先用下看~
