### ISSUE TITLE
当选择每隔几个小时执行一次时，会变成0-N小时，每隔一个小时执行一次

### ISSUE THREAD

**Issue by liEarly** [ssssssss-team/spider-flow#36]
![image](https://user-images.githubusercontent.com/89955149/182269882-6d4f7131-7bc5-4150-b774-d71878d8fbf8.png)

**Comment by nekolr** [comment]
> ![image](https://user-images.githubusercontent.com/89955149/182269882-6d4f7131-7bc5-4150-b774-d71878d8fbf8.png)

maybe fixed
