### ISSUE TITLE
循环节点会打乱数据的顺序

### ISSUE THREAD

**Issue by thinkport** [ssssssss-team/spider-flow#38]
顺序的数据
![1661181792732](https://user-images.githubusercontent.com/12952910/185958399-a332fee2-3244-4322-b1cb-840885fcd147.png)

生成乱序的数据
![1661181853651](https://user-images.githubusercontent.com/12952910/185958576-aa1b7e0b-6298-41cb-b405-8eea69bfec98.png)

爬虫
[sp_flow.txt](https://github.com/ssssssss-team/spider-flow/files/9395621/sp_flow.txt)

这个问题是由多线程引起的，除了使用单线程执行外，还有没有别的办法让数据按顺序插入数据库吗

**Comment by nekolr** [comment]
> 

目前没有，不过你可以尝试自己修改代码处理
