### ISSUE TITLE
Linux下安装提示,jdk.nashorn.api.scripting does not exist,但是jdk是1.8的

### ISSUE THREAD

**Issue by tangzichengcc** [ssssssss-team/spider-flow#40]
[ERROR] /spider-flow/spider-flow-core/src/main/java/org/spiderflow/core/script/ScriptManager.java:[3,33] package jdk.nashorn.api.scripting does not exist

**Comment by nekolr** [comment]
> 

请再确认一下 JDK 环境，nashorn 只有 JDK 8 和 11 有

**Comment by tangzichengcc** [comment]
解决了!谢谢!
