### ISSUE TITLE
Selenium 结点 添加 命令无效

### ISSUE THREAD

**Issue by songsh** [ssssssss-team/spider-flow#9]
![image](https://user-images.githubusercontent.com/2272252/100432539-b272cc80-30d4-11eb-9207-a21a9d1ed142.png)

如图，添加命令没有执行

**Comment by javamxd** [comment]
这里不是这么用的，你这些应该放在执行函数里。

**Comment by songsh** [comment]
我试下.

**Comment by songsh** [comment]
有demo吗，这是有点复杂

**Comment by nekolr** [comment]
> 有demo吗，这是有点复杂

这里设置的是浏览器参数，扩展方法要放到变量里，或者通过函数执行。
